{username, homeDirectory, karabinerSource ? null, gitEmail ? null, hammerspoon ? false}: { config, lib, ... }:

let
  nixConfDir = "${homeDirectory}/dev/nix-conf";

  # Auto-symlink each directory in .config/ to the nix-conf repo
  managedConfigs = builtins.readDir ../.config;
  configDirs = lib.filterAttrs (_: type: type == "directory") managedConfigs;
  configSymlinks = lib.mapAttrs' (name: _: lib.nameValuePair
    ".config/${name}"
    { source = config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/.config/${name}"; }
  ) configDirs;
in
{
  home.username = lib.mkForce username;
  home.homeDirectory = lib.mkForce homeDirectory;
  home.stateVersion = "25.05";

  programs.home-manager.enable = true;

  home.activation.checkNixConfRepo = lib.hm.dag.entryBefore [ "linkGeneration" ] ''
    if [ ! -d "${nixConfDir}" ]; then
      echo "ERROR: nix-conf repo not found at ${nixConfDir}" >&2
      echo "Clone it first, or update the path." >&2
      exit 1
    fi
  '';

  home.file = configSymlinks // lib.optionalAttrs hammerspoon {
    # Out-of-store symlinks so edits apply live, no rebuild
    ".hammerspoon/init.lua".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/hammerspoon/init.lua";
    # Add this directory once in Raycast: Settings → Extensions → + → Add Script Directory
    ".config/raycast-scripts".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/raycast-scripts";
  } // {
    ".hushlogin".text = "";

    ".gitconfig" = if gitEmail != null then {
      text =
        let gitconfigContent = builtins.readFile ./.gitconfig;
        in lib.replaceStrings
          ["email = dev@edt.nz"]
          ["email = ${gitEmail}"]
          gitconfigContent;
    } else {
      source = ./.gitconfig;
    };

    # home.file.".config/karabiner/karabiner.json" = lib.mkIf (karabinerSource != null) {
    #   source = karabinerSource;
    # };

    # pi config files symlinked from the repo (edits write back and sync via git).
    # Runtime state (sessions/, auth.json, models-store.json, npm/, installed
    # extensions) lives in the real ~/.pi/agent dir, never in the repo.
    ".pi/agent/settings.json".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/settings.json";
    ".pi/agent/models.json".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/models.json";
    ".pi/agent/extensions/cmux-sidebar.ts".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/extensions/cmux-sidebar.ts";
    ".pi/agent/extensions/cmux-messaging.ts".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/extensions/cmux-messaging.ts";

    # cmux skills (upstream: github.com/manaflow-ai/cmux, skills/). The
    # cmux-session.ts hook extension is generated by `cmux hooks pi install`
    # into ~/.pi/agent/extensions/ and is not managed here.
    ".pi/agent/skills/cmux/SKILL.md".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/skills/cmux/SKILL.md";
    ".pi/agent/skills/cmux/references/handles-and-identify.md".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/skills/cmux/references/handles-and-identify.md";
    ".pi/agent/skills/cmux/references/panes-surfaces.md".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/skills/cmux/references/panes-surfaces.md";
    ".pi/agent/skills/cmux/references/trigger-flash-and-health.md".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/skills/cmux/references/trigger-flash-and-health.md";
    ".pi/agent/skills/cmux/references/windows-workspaces.md".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/skills/cmux/references/windows-workspaces.md";
    ".pi/agent/skills/cmux-workspace/SKILL.md".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/skills/cmux-workspace/SKILL.md";
    ".pi/agent/skills/cmux-workspace/references/commands.md".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/skills/cmux-workspace/references/commands.md";

    "Library/Services/ghostty_finder.workflow".source = ./ghostty_finder.workflow;

    # home.file."Library/Preferences/eu.exelban.Stats.plist".source = ./Stats.plist;
  };
}