{username, homeDirectory, karabinerSource ? null, gitEmail ? null, hammerspoon ? false}: { config, lib, ... }:

let
  nixConfDir = "${homeDirectory}/dev/nix-conf";

  # Auto-symlink each directory in .config/ to the nix-conf repo
  managedConfigs = builtins.readDir ../.config;
  configDirs = lib.filterAttrs (_: type: type == "directory") managedConfigs;
  configSymlinks = lib.mapAttrs' (name: _: lib.nameValuePair
    ".config/${name}"
    { source = config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/.config/${name}"; }
  ) configDirs;

  # Every file under darwin/pi-agent/skills/ (cmux, cmux-workspace,
  # cmux-browser, cmux-markdown, cmux-settings — upstream manaflow-ai/cmux)
  # symlinked into ~/.pi/agent/skills/ with the same relative layout.
  piSkillEntries = let
    skillsRoot = "${nixConfDir}/darwin/pi-agent/skills";
    rel = p: builtins.substring (builtins.stringLength skillsRoot + 1) (builtins.stringLength p) p;
    walk = dir: builtins.concatLists (map (name: let
      p = "${dir}/${name}";
      t = (builtins.readDir dir).${name};
    in if t == "directory"
       then walk p
       else [ { name = ".pi/agent/skills/${rel p}"; value = { source = config.lib.file.mkOutOfStoreSymlink p; }; } ])
      (builtins.attrNames (builtins.readDir dir)));
  in builtins.listToAttrs (walk skillsRoot);
in
{
  home.username = lib.mkForce username;
  home.homeDirectory = lib.mkForce homeDirectory;
  home.stateVersion = "25.05";

  programs.home-manager.enable = true;

  home.activation.checkNixConfRepo = lib.hm.dag.entryBefore [ "linkGeneration" ] ''
    if [ ! -d "${nixConfDir}" ]; then
      echo "ERROR: nix-conf repo not found at ${nixConfDir}" >&2
      echo "Clone it first, or update the path." >&2
      exit 1
    fi
  '';

  home.file = configSymlinks // piSkillEntries // lib.optionalAttrs hammerspoon {
    # Out-of-store symlinks so edits apply live, no rebuild
    ".hammerspoon/init.lua".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/hammerspoon/init.lua";
    # Add this directory once in Raycast: Settings → Extensions → + → Add Script Directory
    ".config/raycast-scripts".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/raycast-scripts";
  } // {
    ".hushlogin".text = "";

    ".gitconfig" = if gitEmail != null then {
      text =
        let gitconfigContent = builtins.readFile ./.gitconfig;
        in lib.replaceStrings
          ["email = dev@edt.nz"]
          ["email = ${gitEmail}"]
          gitconfigContent;
    } else {
      source = ./.gitconfig;
    };

    # home.file.".config/karabiner/karabiner.json" = lib.mkIf (karabinerSource != null) {
    #   source = karabinerSource;
    # };

    # pi config files symlinked from the repo (edits write back and sync via git).
    # Runtime state (sessions/, auth.json, models-store.json, npm/, installed
    # extensions) lives in the real ~/.pi/agent dir, never in the repo.
    ".pi/agent/settings.json".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/settings.json";
    ".pi/agent/models.json".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/models.json";
    ".pi/agent/extensions/cmux-sidebar.ts".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/extensions/cmux-sidebar.ts";
    ".pi/agent/extensions/cmux-messaging.ts".source =
      config.lib.file.mkOutOfStoreSymlink "${nixConfDir}/darwin/pi-agent/extensions/cmux-messaging.ts";

    # cmux-session.ts (official hook extension) is generated by
    # `cmux hooks pi install` into ~/.pi/agent/extensions/ — not managed here.

    "Library/Services/ghostty_finder.workflow".source = ./ghostty_finder.workflow;

    # home.file."Library/Preferences/eu.exelban.Stats.plist".source = ./Stats.plist;
  };
}